### ISSUE TITLE
dotnet 1.0.4 and xaml?

### ISSUE THREAD

**Issue by GregDomjan** [kaspersorensen/dotnet-maven-plugin#14]
I was looking using this plugin in trying to build this sample 
https://github.com/MicrosoftEdge/MicrosoftEdge-Extensions-Demos/tree/master/SecureInput

I got stuck on the AppContainerExe and UniversalWindows UAP.
Seemed to be getting stuck on not finding xaml targets in dotnet folders, I think I found eventually that it is just not supported yet for dotnet core.  
Seemed to be targeting older VS14 instead of VS15 (2017) but attempting to force version setting min didn't resolve. I didn't see anything for the plugin that would allow to specify, only setting in csproj.

Any hints?

Also tried migrating to new csproj format but couldn't get it to accept UAP build fully and SDKReference wasn't resolving.

**Comment by kaspersorensen** [comment]
I think your issue is with .NET core SDK, not this maven plugin. Generally speaking, the plugin will issue commands such as `dotnet restore`, `dotnet build` etc. If those commands fail in themselves, then the plugin can't do anything to fix it really.

I'm not super experienced in making the `dotnet` command work with non-core builds, but I have seen a few examples where other frameworks are defined in project.json. Kinda like this (just a snippet that I can't say will work for the specific project you're talking about):

```
 "frameworks" : {
    "net45" : {
      "dependencies" : {
        "Newtonsoft.Json" : "7.0.1",
        "Microsoft.Extensions.Primitives" : "1.1.0",
        "Microsoft.Net.Http" : "2.2.22"
      },
      "frameworkAssemblies" : {
        "System.Web" : "4.0.0.0"
      }
    }
}
```

Good luck. I'm gonna close this issue though since the problem you have is not maven plugin related.
